[package]
name = "gqlrequest"
version = "0.1.1"
authors = ["Filip Bucek <fbucek@invloop.cz>"]
edition = "2018"

[dependencies]
eyre = "0.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
