[package]
name = "gqlrequest"
version = "0.1.1-alpha.0"
authors = ["Filip Bucek <filip.bucek@icsystems.ai>"]
edition = "2018"

[dependencies]
tracing = "0.1"
eyre = "0.6"
color-eyre = "0.5"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
